var SHOUTOUT_FEE = "0.0000001"; // amount to pay for listing
// Main Native Minima address is of this type
var MAIN_ADDRESS = "LET type=[dex address] RETURN SIGNEDBY(*)";

var DEX_CONTRACT =
  "LET randid=[ DEX Contract v 1.1 ] LET ownerkey=PREVSTATE(0) ASSERT VERIFYOUT(@INPUT 0xFFEEDD8888 0.0001 0x00 TRUE) IF SIGNEDBY(ownerkey) THEN RETURN TRUE ENDIF LET owneraddress=PREVSTATE(1) LET tokenid=PREVSTATE(2) LET tokenamount=PREVSTATE(3) LET taker=PREVSTATE(4) ASSERT SAMESTATE(66 66) IF taker NEQ 0x00 THEN ASSERT SIGNEDBY(taker) ENDIF RETURN VERIFYOUT(@INPUT+2 owneraddress tokenamount tokenid FALSE)";
var DEX_ADDRESS =
  "MxG082F8EJ6F2T61Z6T1UW3025H0EMYWQZVC2U0C8BAZA136P8BDR6K8ZRKFFN0";

// var LISTING_CONTRACT =
//   "LET randid=[ Order Book Contract v 1.1 ] LET ownerkey=PREVSTATE(0) IF SIGNEDBY(ownerkey) THEN RETURN TRUE ENDIF";
// var OLD_LISTING_ADDRESS =
//   "Mx1004GRQMTTBDERBMQTY1YCBYQ";
var LISTING_ADDRESS =
  "0xDEADDEADDEADDEAD44";

var COIN_EVENT_NOTIFY = "0xFFEEDD8888";

